initial botany_dales document
eurec4a/how_to_eurec4a pull request #81
Opened 2022-06-16 16:01 UTC by fjansson

Draft pull request for the botany dataset.

- [x] introduction to botany experiment (what has been done, further resources)
- [x] example on how to open a botany experiment
- [x] example on how to read experiment parameters
- [x] describe which experiments (resolution, size, etc.) are available

2022-07-28 23:23 UTC, observingClouds commented
With merged, this notebook works as well. I just re-run your PR in my own fork successfully: https://github.com/observingClouds/how_to_eurec4a/actions/runs/2757007834

I edited the header to mark the things that still need to be addressed before we can merge this.

2022-11-02 13:28 UTC, martinjanssens commented
@observingClouds @fjansson I've had an initial go at this, see https://github.com/martinjanssens/how_to_eurec4a/tree/botany. It could perhaps use a little more background information, we should eventually include our data set paper and the appropriate reference and we might consider waiting to merge this until after we've merged https://github.com/eurec4a/eurec4a-intake/pull/128, as I'm still referring to Hauke's private branch of `eurec4a-intake` to get the most up-to-date catalog entries here. I.e. this:

```
from intake import open_catalog
url = "https://raw.githubusercontent.com/observingClouds/eurec4a-intake/botany/catalog.yml"
cat = open_catalog(url)
```

Should eventually just be this:

```
import eurec4a
cat = eurec4a.get_intake_catalog()
```

2022-11-02 17:56 UTC, observingClouds commented
@martinjanssens thanks for taking this further! I just compiled the book locally. It looks good so far. Could you please add your branch to this branch (fjansson/how_to_eurec4a) or merge this one into yours and create a new PR so that we can discuss the details alongside the code?

2022-11-02 18:39 UTC, martinjanssens commented
Agreed, done!

2022-11-02 20:44 UTC, observingClouds requested changes
Great work! I just marked a few minor suggestions. Could we maybe also create an example where the hyper-cube is actually used? I imagine an example where we show one quantity and its change along one hyper-cub dimension from the "center" to a "corner".

2022-11-03 17:36 UTC, observingClouds commented on how_to_eurec4a/botany_dales.md
> +Cloud Botany is a library of idealised large-eddy simulations forced by and initialised with combinations of simplified vertical profiles, parameterised by variables which span a range of conditions
How about this suggestion?

2022-11-03 17:43 UTC, observingClouds commented on how_to_eurec4a/botany_dales.md
> +`parameters` contains the value of the variables in {numref}`botany-variables`, as they vary for each `member` of the ensemble. The ensemble may be thought of a hypercube in the six-dimensional space
Is `du/dz` missing here on purpose, or is it actually a seventh-dimensional space? 🤯

2022-11-03 17:43 UTC, observingClouds commented on how_to_eurec4a/botany_dales.md
> +```
Awesome 🥳 this is exactly what I had in mind as it shows nicely how to combine the parameters with the simulation output! Thanks @martinjanssens !

2022-11-03 20:24 UTC, martinjanssens commented on how_to_eurec4a/botany_dales.md
> +`parameters` contains the value of the variables in {numref}`botany-variables`, as they vary for each `member` of the ensemble. The ensemble may be thought of a hypercube in the six-dimensional space
It's technically a 7-dimensional space I guess, since we do vary `dudz`, but only do so for a single sweep. It's kept constant otherwise. So actually, it's practically somewhere between a 6 and 7 dimensional space. My head hurts! I've stuck in a footnote to address this.

2022-11-03 22:52 UTC, observingClouds commented on how_to_eurec4a/botany_dales.md
> +`parameters` contains the value of the variables in {numref}`botany-variables`, as they vary for each `member` of the ensemble. The ensemble may be thought of a hypercube in the six-dimensional space
Thanks for clarifying this!

2022-11-03 23:01 UTC, observingClouds approved these changes

2022-11-18 03:17 UTC, observingClouds commented
@martinjanssens we are getting closer to the finish line! Could you please update this PR now that the intake catalog contains the botany dataset?

2022-11-18 07:27 UTC, observingClouds approved these changes
Well done @martinjanssens and @fjansson! That's it!

2022-11-18 07:30 UTC, martinjanssens commented
Thanks a lot to you, Hauke!

2022-11-18 07:30 UTC, merged